version: '2'
services:
    web:
        build: .
        ports: 
            - "5000:5000"  # Host:Container
        volumes:
            - .:/app  # Link the current directory to the /app directory in the container
